name = "xraycrypto-news"
main = "cloudflare-worker-news.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
# Add any public environment variables here

[[kv_namespaces]]
binding = "MARKET_KV"
id = "2f25cb6f358842028bceb61cb55c9f3d"
preview_id = "2f25cb6f358842028bceb61cb55c9f3d"

# Cron trigger for generating market briefs twice daily
[triggers]
crons = ["0 12 * * *", "0 21 * * *"]

# Environment variables for secrets (set via wrangler secret put)
# OPENAI_API_KEY - Your OpenAI API key (set via: wrangler secret put OPENAI_API_KEY)

[build]
command = ""

[env.production]
name = "xraycrypto-news"

[env.staging]
name = "xraycrypto-news-staging"