// Top 100 Cryptocurrencies by Market Cap - December 2024
// Source: CoinGecko

export const TOP_100_MARKET_CAP = [
  { rank: 1, symbol: "BTC", name: "Bitcoin" },
  { rank: 2, symbol: "ETH", name: "Ethereum" },
  { rank: 3, symbol: "USDT", name: "Tether" },
  { rank: 4, symbol: "XRP", name: "XRP" },
  { rank: 5, symbol: "BNB", name: "BNB" },
  { rank: 6, symbol: "SOL", name: "Solana" },
  { rank: 7, symbol: "USDC", name: "USDC" },
  { rank: 8, symbol: "TRX", name: "TRON" },
  { rank: 9, symbol: "STETH", name: "Lido Staked Ether" },
  { rank: 10, symbol: "DOGE", name: "Dogecoin" },
  { rank: 11, symbol: "ADA", name: "Cardano" },
  { rank: 12, symbol: "FIGR_HELOC", name: "Figure Heloc" },
  { rank: 13, symbol: "WSTETH", name: "Wrapped stETH" },
  { rank: 14, symbol: "WBTC", name: "Wrapped Bitcoin" },
  { rank: 15, symbol: "WBT", name: "WhiteBIT Coin" },
  { rank: 16, symbol: "WBETH", name: "Wrapped Beacon ETH" },
  { rank: 17, symbol: "HYPE", name: "Hyperliquid" },
  { rank: 18, symbol: "ZEC", name: "Zcash" },
  { rank: 19, symbol: "LINK", name: "Chainlink" },
  { rank: 20, symbol: "BCH", name: "Bitcoin Cash" },
  { rank: 21, symbol: "USDS", name: "USDS" },
  { rank: 22, symbol: "BSC-USD", name: "Binance Bridged USDT (BNB Smart Chain)" },
  { rank: 23, symbol: "LEO", name: "LEO Token" },
  { rank: 24, symbol: "WETH", name: "WETH" },
  { rank: 25, symbol: "XLM", name: "Stellar" },
  { rank: 26, symbol: "WEETH", name: "Wrapped eETH" },
  { rank: 27, symbol: "USDE", name: "Ethena USDe" },
  { rank: 28, symbol: "LTC", name: "Litecoin" },
  { rank: 29, symbol: "XMR", name: "Monero" },
  { rank: 30, symbol: "CBBTC", name: "Coinbase Wrapped BTC" },
  { rank: 31, symbol: "HBAR", name: "Hedera" },
  { rank: 32, symbol: "AVAX", name: "Avalanche" },
  { rank: 33, symbol: "SUI", name: "Sui" },
  { rank: 34, symbol: "SHIB", name: "Shiba Inu" },
  { rank: 35, symbol: "DOT", name: "Polkadot" },
  { rank: 36, symbol: "TON", name: "Toncoin" },
  { rank: 37, symbol: "SUSDE", name: "Ethena Staked USDe" },
  { rank: 38, symbol: "DAI", name: "Dai" },
  { rank: 39, symbol: "UNI", name: "Uniswap" },
  { rank: 40, symbol: "CRO", name: "Cronos" },
  { rank: 41, symbol: "CC", name: "Canton" },
  { rank: 42, symbol: "USDT0", name: "USDT0" },
  { rank: 43, symbol: "WLFI", name: "World Liberty Financial" },
  { rank: 44, symbol: "M", name: "MemeCore" },
  { rank: 45, symbol: "MNT", name: "Mantle" },
  { rank: 46, symbol: "SUSDS", name: "sUSDS" },
  { rank: 47, symbol: "PYUSD", name: "PayPal USD" },
  { rank: 48, symbol: "TAO", name: "Bittensor" },
  { rank: 49, symbol: "NEAR", name: "NEAR Protocol" },
  { rank: 50, symbol: "ICP", name: "Internet Computer" },
  { rank: 51, symbol: "USD1", name: "USD1" },
  { rank: 52, symbol: "BGB", name: "Bitget Token" },
  { rank: 53, symbol: "AAVE", name: "Aave" },
  { rank: 54, symbol: "C1USD", name: "Currency One USD" },
  { rank: 55, symbol: "BUIDL", name: "BlackRock USD Institutional Digital Liquidity Fund" },
  { rank: 56, symbol: "OKB", name: "OKB" },
  { rank: 57, symbol: "ETC", name: "Ethereum Classic" },
  { rank: 58, symbol: "ASTER", name: "Aster" },
  { rank: 59, symbol: "APT", name: "Aptos" },
  { rank: 60, symbol: "XAUT", name: "Tether Gold" },
  { rank: 61, symbol: "USDF", name: "Falcon USD" },
  { rank: 62, symbol: "PEPE", name: "Pepe" },
  { rank: 63, symbol: "ENA", name: "Ethena" },
  { rank: 64, symbol: "PUMP", name: "Pump.fun" },
  { rank: 65, symbol: "JITOSOL", name: "Jito Staked SOL" },
  { rank: 66, symbol: "JLP", name: "Jupiter Perpetuals Liquidity Provider Token" },
  { rank: 67, symbol: "WETH", name: "Binance-Peg WETH" },
  { rank: 68, symbol: "SOL", name: "Wrapped SOL" },
  { rank: 69, symbol: "ONDO", name: "Ondo" },
  { rank: 70, symbol: "PI", name: "Pi Network" },
  { rank: 71, symbol: "HTX", name: "HTX DAO" },
  { rank: 72, symbol: "WLD", name: "Worldcoin" },
  { rank: 73, symbol: "POL", name: "POL (ex-MATIC)" },
  { rank: 74, symbol: "KCS", name: "KuCoin" },
  { rank: 75, symbol: "USDTB", name: "USDtb" },
  { rank: 76, symbol: "HASH", name: "Provenance Blockchain" },
  { rank: 77, symbol: "TRUMP", name: "Official Trump" },
  { rank: 78, symbol: "ALGO", name: "Algorand" },
  { rank: 79, symbol: "FIL", name: "Filecoin" },
  { rank: 80, symbol: "PAXG", name: "PAX Gold" },
  { rank: 81, symbol: "RETH", name: "Rocket Pool ETH" },
  { rank: 82, symbol: "ATOM", name: "Cosmos Hub" },
  { rank: 83, symbol: "SYRUPUSDT", name: "syrupUSDT" },
  { rank: 84, symbol: "VET", name: "VeChain" },
  { rank: 85, symbol: "BFUSD", name: "BFUSD" },
  { rank: 86, symbol: "ARB", name: "Arbitrum" },
  { rank: 87, symbol: "USDC", name: "Binance Bridged USDC (BNB Smart Chain)" },
  { rank: 88, symbol: "BNSOL", name: "Binance Staked SOL" },
  { rank: 89, symbol: "GT", name: "Gate" },
  { rank: 90, symbol: "KHYPE", name: "Kinetiq Staked HYPE" },
  { rank: 91, symbol: "WBNB", name: "Wrapped BNB" },
  { rank: 92, symbol: "SYRUPUSDC", name: "syrupUSDC" },
  { rank: 93, symbol: "KAS", name: "Kaspa" },
  { rank: 94, symbol: "QNT", name: "Quant" },
  { rank: 95, symbol: "SKY", name: "Sky" },
  { rank: 96, symbol: "FBTC", name: "Function FBTC" },
  { rank: 97, symbol: "USDG", name: "Global Dollar" },
  { rank: 98, symbol: "RSETH", name: "Kelp DAO Restaked ETH" },
  { rank: 99, symbol: "FLR", name: "Flare" },
  { rank: 100, symbol: "RLUSD", name: "Ripple USD" },
] as const;

// Fast lookup map: symbol -> rank
export const MARKET_CAP_RANKS: Record<string, number> = Object.fromEntries(
  TOP_100_MARKET_CAP.map(t => [t.symbol, t.rank])
);

// Helper function with 9999 fallback for unlisted tokens
export function getMarketCapRank(symbol: string): number {
  return MARKET_CAP_RANKS[symbol?.toUpperCase()] ?? 9999;
}
