// Top Cryptocurrencies by Market Cap - TradingView Screener December 2024
// Source: TradingView Crypto Screener

export const TOP_100_MARKET_CAP = [
  { rank: 1, symbol: "BTC", name: "Bitcoin" },
  { rank: 2, symbol: "ETH", name: "Ethereum" },
  { rank: 3, symbol: "XRP", name: "XRP" },
  { rank: 4, symbol: "USDT", name: "Tether" },
  { rank: 5, symbol: "SOL", name: "Solana" },
  { rank: 6, symbol: "BNB", name: "BNB" },
  { rank: 7, symbol: "DOGE", name: "Dogecoin" },
  { rank: 8, symbol: "USDC", name: "USDC" },
  { rank: 9, symbol: "ADA", name: "Cardano" },
  { rank: 10, symbol: "TRX", name: "TRON" },
  { rank: 11, symbol: "HYPE", name: "Hyperliquid" },
  { rank: 12, symbol: "AVAX", name: "Avalanche" },
  { rank: 13, symbol: "LINK", name: "Chainlink" },
  { rank: 14, symbol: "SUI", name: "Sui" },
  { rank: 15, symbol: "XLM", name: "Stellar" },
  { rank: 16, symbol: "SHIB", name: "Shiba Inu" },
  { rank: 17, symbol: "TON", name: "Toncoin" },
  { rank: 18, symbol: "HBAR", name: "Hedera" },
  { rank: 19, symbol: "BCH", name: "Bitcoin Cash" },
  { rank: 20, symbol: "DOT", name: "Polkadot" },
  { rank: 21, symbol: "LTC", name: "Litecoin" },
  { rank: 22, symbol: "UNI", name: "Uniswap" },
  { rank: 23, symbol: "LEO", name: "LEO Token" },
  { rank: 24, symbol: "PEPE", name: "Pepe" },
  { rank: 25, symbol: "NEAR", name: "NEAR Protocol" },
  { rank: 26, symbol: "APT", name: "Aptos" },
  { rank: 27, symbol: "DAI", name: "Dai" },
  { rank: 28, symbol: "ICP", name: "Internet Computer" },
  { rank: 29, symbol: "AAVE", name: "Aave" },
  { rank: 30, symbol: "ETC", name: "Ethereum Classic" },
  { rank: 31, symbol: "CRO", name: "Cronos" },
  { rank: 32, symbol: "MNT", name: "Mantle" },
  { rank: 33, symbol: "POL", name: "POL (ex-MATIC)" },
  { rank: 34, symbol: "RENDER", name: "Render" },
  { rank: 35, symbol: "VET", name: "VeChain" },
  { rank: 36, symbol: "FET", name: "Fetch.ai" },
  { rank: 37, symbol: "KAS", name: "Kaspa" },
  { rank: 38, symbol: "ARB", name: "Arbitrum" },
  { rank: 39, symbol: "OM", name: "MANTRA" },
  { rank: 40, symbol: "FIL", name: "Filecoin" },
  { rank: 41, symbol: "ATOM", name: "Cosmos Hub" },
  { rank: 42, symbol: "TAO", name: "Bittensor" },
  { rank: 43, symbol: "ALGO", name: "Algorand" },
  { rank: 44, symbol: "OKB", name: "OKB" },
  { rank: 45, symbol: "STX", name: "Stacks" },
  { rank: 46, symbol: "THETA", name: "Theta Network" },
  { rank: 47, symbol: "INJ", name: "Injective" },
  { rank: 48, symbol: "IMX", name: "Immutable" },
  { rank: 49, symbol: "JUP", name: "Jupiter" },
  { rank: 50, symbol: "GRT", name: "The Graph" },
  { rank: 51, symbol: "WIF", name: "dogwifhat" },
  { rank: 52, symbol: "BONK", name: "Bonk" },
  { rank: 53, symbol: "OP", name: "Optimism" },
  { rank: 54, symbol: "FTM", name: "Fantom" },
  { rank: 55, symbol: "FLOKI", name: "Floki" },
  { rank: 56, symbol: "WLD", name: "Worldcoin" },
  { rank: 57, symbol: "SEI", name: "Sei" },
  { rank: 58, symbol: "ONDO", name: "Ondo" },
  { rank: 59, symbol: "XMR", name: "Monero" },
  { rank: 60, symbol: "EOS", name: "EOS" },
  { rank: 61, symbol: "JASMY", name: "JasmyCoin" },
  { rank: 62, symbol: "LDO", name: "Lido DAO" },
  { rank: 63, symbol: "TIA", name: "Celestia" },
  { rank: 64, symbol: "QNT", name: "Quant" },
  { rank: 65, symbol: "PYTH", name: "Pyth Network" },
  { rank: 66, symbol: "MKR", name: "Maker" },
  { rank: 67, symbol: "SAND", name: "The Sandbox" },
  { rank: 68, symbol: "GALA", name: "Gala" },
  { rank: 69, symbol: "BEAM", name: "Beam" },
  { rank: 70, symbol: "ENS", name: "Ethereum Name Service" },
  { rank: 71, symbol: "KCS", name: "KuCoin" },
  { rank: 72, symbol: "XDC", name: "XDC Network" },
  { rank: 73, symbol: "FLOW", name: "Flow" },
  { rank: 74, symbol: "KAIA", name: "Kaia" },
  { rank: 75, symbol: "BRETT", name: "Brett" },
  { rank: 76, symbol: "RUNE", name: "THORChain" },
  { rank: 77, symbol: "AXS", name: "Axie Infinity" },
  { rank: 78, symbol: "IOTA", name: "IOTA" },
  { rank: 79, symbol: "FLR", name: "Flare" },
  { rank: 80, symbol: "AIOZ", name: "AIOZ Network" },
  { rank: 81, symbol: "NEXO", name: "Nexo" },
  { rank: 82, symbol: "XTZ", name: "Tezos" },
  { rank: 83, symbol: "VIRTUAL", name: "Virtuals Protocol" },
  { rank: 84, symbol: "MANA", name: "Decentraland" },
  { rank: 85, symbol: "STRK", name: "Starknet" },
  { rank: 86, symbol: "MON", name: "Mon Protocol" },
  { rank: 87, symbol: "AERO", name: "Aerodrome Finance" },
  { rank: 88, symbol: "CRV", name: "Curve DAO" },
  { rank: 89, symbol: "ZEC", name: "Zcash" },
  { rank: 90, symbol: "BSV", name: "Bitcoin SV" },
  { rank: 91, symbol: "PENGU", name: "Pudgy Penguins" },
  { rank: 92, symbol: "MOVE", name: "Movement" },
  { rank: 93, symbol: "NEO", name: "NEO" },
  { rank: 94, symbol: "ENA", name: "Ethena" },
  { rank: 95, symbol: "DEXE", name: "DeXe" },
  { rank: 96, symbol: "SPX", name: "SPX6900" },
  { rank: 97, symbol: "COMP", name: "Compound" },
  { rank: 98, symbol: "POPCAT", name: "Popcat" },
  { rank: 99, symbol: "CORE", name: "Core" },
  { rank: 100, symbol: "CFX", name: "Conflux" },
  { rank: 101, symbol: "EGLD", name: "MultiversX" },
  { rank: 102, symbol: "APE", name: "ApeCoin" },
  { rank: 103, symbol: "BLUR", name: "Blur" },
  { rank: 104, symbol: "AKT", name: "Akash Network" },
  { rank: 105, symbol: "MEW", name: "cat in a dogs world" },
  { rank: 106, symbol: "ZRO", name: "LayerZero" },
  { rank: 107, symbol: "BAT", name: "Basic Attention Token" },
  { rank: 108, symbol: "RNDR", name: "Render Token" },
  { rank: 109, symbol: "FARTCOIN", name: "Fartcoin" },
  { rank: 110, symbol: "CAKE", name: "PancakeSwap" },
  { rank: 111, symbol: "TRUMP", name: "Official Trump" },
  { rank: 112, symbol: "MORPHO", name: "Morpho" },
  { rank: 113, symbol: "GRASS", name: "Grass" },
  { rank: 114, symbol: "BTT", name: "BitTorrent" },
  { rank: 115, symbol: "PNUT", name: "Peanut the Squirrel" },
  { rank: 116, symbol: "AITECH", name: "Solidus AI Tech" },
  { rank: 117, symbol: "ACT", name: "Act I: The AI Prophecy" },
  { rank: 118, symbol: "MASK", name: "Mask Network" },
  { rank: 119, symbol: "SNCE", name: "Salmonation" },
  { rank: 120, symbol: "SUPRA", name: "Supra" },
  { rank: 121, symbol: "CELO", name: "Celo" },
  { rank: 122, symbol: "VTHO", name: "VeThor Token" },
  { rank: 123, symbol: "RSR", name: "Reserve Rights" },
  { rank: 124, symbol: "SNX", name: "Synthetix" },
  { rank: 125, symbol: "SAFE", name: "Safe" },
  { rank: 126, symbol: "SUPER", name: "SuperVerse" },
  { rank: 127, symbol: "NEIRO", name: "First Neiro On Ethereum" },
  { rank: 128, symbol: "HNT", name: "Helium" },
  { rank: 129, symbol: "1INCH", name: "1inch" },
  { rank: 130, symbol: "PONKE", name: "Ponke" },
  { rank: 131, symbol: "ZIL", name: "Zilliqa" },
  { rank: 132, symbol: "ZK", name: "ZKsync" },
  { rank: 133, symbol: "WEMIX", name: "WEMIX" },
  { rank: 134, symbol: "DYDX", name: "dYdX" },
  { rank: 135, symbol: "GOAT", name: "Goatseus Maximus" },
  { rank: 136, symbol: "WLFI", name: "Wen Lambo Financial" },
  { rank: 137, symbol: "PAAL", name: "PAAL AI" },
  { rank: 138, symbol: "TURBO", name: "Turbo" },
  { rank: 139, symbol: "MOCA", name: "Moca Network" },
  { rank: 140, symbol: "NOT", name: "Notcoin" },
  { rank: 141, symbol: "GLM", name: "Golem" },
  { rank: 142, symbol: "RPL", name: "Rocket Pool" },
  { rank: 143, symbol: "AR", name: "Arweave" },
] as const;

// Fast lookup map: symbol -> rank
export const MARKET_CAP_RANKS: Record<string, number> = Object.fromEntries(
  TOP_100_MARKET_CAP.map(t => [t.symbol, t.rank])
);

// Helper function with 9999 fallback for unlisted tokens
export function getMarketCapRank(symbol: string): number {
  return MARKET_CAP_RANKS[symbol?.toUpperCase()] ?? 9999;
}
